# docker run -d --rm --name mongo -p 27017:27017 -v /absolute/path/to/mongodbdata:/data/db mongo:latest

version: "3.8"
services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodbdata:/data/db

volumes:
  mongodbdata:
